name: Windows Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.7.2
  ARTIFACT:     GaussianBeam.zip

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{ env.QT_VERSION }}
          host: ${{ matrix.os == 'ubuntu-latest' && 'linux' || 'windows' }}
          target: desktop
          arch: ${{ matrix.os == 'ubuntu-latest' && 'linux_gcc_64' || 'win64_msvc2019_64' }}
          archives: qtbase
          setup-python: false
          cache: true
          dir: ${{ runner.temp }}

      - name: Install Ninja (Linux)
        run: sudo apt-get install ninja-build
        if: matrix.os == 'ubuntu-latest'

      - name: Install Ninja (windows)
        run: choco install ninja
        if: matrix.os == 'windows-latest'

      - name: Install Ninja (macOS)
        run: brew install ninja
        if: matrix.os == 'macos-latest'

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run:  >
              cmake
              -S .
              -B build
              -G "Ninja Multi-Config"
              && cmake --build build --config Release
              
      - name: Zip build
        run:  |
              7z a ${{ env.ARTIFACT }} ./build/* -r
              
      - name: (10) Save build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ./${{ env.ARTIFACT }}